### ISSUE TITLE
void (async () => {

### ISSUE THREAD

**Issue by tobiasmuehl** [nramkissoon/t3-stripe#4]
https://github.com/nramkissoon/t3-stripe/blob/62ccf96606b02eba64244d9aadb6345317943d56/src/pages/dashboard.tsx#L30

The onClick handler doesn't do anything for me. I checked and it's because of the `void (async () => {` thing. What is that for? Hard to find it documented anywhere.

Not working

```tsx
    <button
      onClick={() =>
        void (async () => {
          alert('yes I am using alert for debugging even tho its 2023 :(')
        })
      }
    >
```

working

```tsx
    <button
      onClick={() =>
        (async () => {
          alert('yes I am using alert for debugging even tho its 2023 :(')
        })()
      }
    >
```

**Comment by tobiasmuehl** [comment]
Ok, I found [some docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void#non-leaking_arrow_functions) but nevertheless, it doesn't actually work for me.

<img width="337" alt="Screenshot 2023-03-09 at 17 51 39" src="https://user-images.githubusercontent.com/3341826/224002413-5ac69239-ac13-4a7e-ba4d-6488b924d6d9.png">

**Comment by nramkissoon** [comment]
Hi, that weird void syntax was to avoid this [eslint error](https://typescript-eslint.io/rules/no-floating-promises). Adding [this rule](https://github.com/react-hook-form/react-hook-form/discussions/8622?sort=old#discussioncomment-4060570) to eslintrc.cjs allows you to avoid it and do this:
```
<button
      onClick={async () => {
          alert('yes I am using alert for debugging even tho its 2023)
        }
      }
    >
```

That eslint rule does not come as a default in the base .eslintrc.cjs so I'm not sure if it's the best way to handle it. Will continue to look into it.

**Comment by tobiasmuehl** [comment]
I don't think I changed my ESLint config and I don't get any warnings/errors. I've removed the void operator and am quite happy now.

**Comment by nramkissoon** [comment]
Sounds good, just updated the repo and tutorial article
